name: 'Matt Henson Productions '
favicon: null
layout_spectrum: 0.88283
typography_spectrum: 0.2137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#de7a1c'
    - '#396f8f'
    - '#b4c6cf'
    - '#6d8ea1'
  brandStrength: 0.5426532651763409
  lightness: 0.375
  saturation: 0.3025708021596074
  rhythmicContrast: 0.75
purpose: []
